import { cssMap } from "@atlaskit/css";
import { token } from "@atlaskit/tokens";

export const styles = cssMap({
  page: {
    minHeight: "100vh",
    backgroundColor: token("color.background.neutral"),
    color: token("color.text"),
  },
  shell: {
    display: "grid",
    gridTemplateColumns: "16rem minmax(0, 1fr)",
    minHeight: "100vh",
  },
  sidebar: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    padding: token("space.300"),
    backgroundColor: token("elevation.surface"),
    borderInlineEndColor: token("color.border"),
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: token("border.width"),
  },
  main: { minWidth: 0 },
  mainInner: {
    maxWidth: "90rem",
    marginInline: "auto",
    paddingBlock: token("space.400"),
    paddingInline: token("space.500"),
  },
  auth: {
    minHeight: "100vh",
    display: "grid",
    placeItems: "center",
    padding: token("space.500"),
    backgroundColor: token("color.background.neutral"),
  },
  authCard: {
    width: "min(32rem, 100%)",
    padding: token("space.500"),
    backgroundColor: token("elevation.surface.raised"),
    borderColor: token("color.border"),
    borderStyle: "solid",
    borderWidth: token("border.width"),
    borderRadius: token("radius.large"),
  },
  panel: {
    backgroundColor: token("elevation.surface.raised"),
    borderColor: token("color.border"),
    borderStyle: "solid",
    borderWidth: token("border.width"),
    borderRadius: token("radius.medium"),
  },
  header: {
    paddingBlockEnd: token("space.300"),
    borderBlockEndColor: token("color.border"),
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: token("border.width"),
  },
  builderGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.35fr) minmax(20rem, 0.8fr)",
    gap: token("space.300"),
  },
  bottomGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.35fr) minmax(20rem, 0.8fr)",
    gap: token("space.300"),
  },
  panelPadding: { padding: token("space.400") },
  runSummary: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: token("space.400"),
    backgroundColor: token("color.background.information"),
    borderColor: token("color.border.information"),
    borderStyle: "solid",
    borderWidth: token("border.width"),
    borderRadius: token("radius.medium"),
  },
  stepRow: {
    width: "100%",
    display: "flex",
    alignItems: "flex-start",
    gap: token("space.200"),
    paddingBlock: token("space.150"),
    paddingInline: token("space.200"),
    textAlign: "start",
    backgroundColor: token("elevation.surface.raised"),
    borderColor: token("color.border"),
    borderStyle: "solid",
    borderWidth: token("border.width"),
    borderRadius: token("radius.medium"),
    cursor: "pointer",
    "&:hover": { backgroundColor: token("color.background.neutral.hovered") },
  },
  stepRowSelected: {
    backgroundColor: token("color.background.selected"),
    borderColor: token("color.border.selected"),
  },
  stepIcon: {
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    padding: token("space.100"),
    color: token("color.text.brand"),
    backgroundColor: token("color.background.brand.subtlest"),
    borderRadius: token("radius.small"),
  },
  fieldSurface: {
    padding: token("space.300"),
    backgroundColor: token("color.background.neutral"),
    borderRadius: token("radius.medium"),
  },
  navItem: {
    width: "100%",
    justifyContent: "flex-start",
  },
  footer: {
    marginBlockStart: "auto",
    paddingBlockStart: token("space.300"),
    borderBlockStartColor: token("color.border"),
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: token("border.width"),
  },
  tableCell: { whiteSpace: "nowrap" },
});
